version: '3'

services:
    golang-web:
        container_name: golang-web
        image: golang-sample/web
        build: ./web
        volumes:
            - "../../:/go"
        ports:
            - '5000:5000'
        networks:
            golang:
                ipv4_address: 172.22.0.11

networks:
    golang:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.22.0.0/24
